
import { Content } from './types';


export const MOCK_CONTENT: Content[] = [
  {
    id: '1',
    type: 'movie',
    title: 'RH NULO',
    description: 'Su hermana murió cuando tenía 5 años y sus padres nunca lo dejaron salir, hasta que al cumplir los 16 lo dejaron ir a una preparatoria normal por primera vez, ¿Quién diría que eso cambiaría su vida?',
    thumbnailUrl: 'https://ik.imagekit.io/gzrwng096/RH%20Nulo/maxresdefault%20(2).jpg?updatedAt=1751921520460',
    backdropUrl: 'https://ik.imagekit.io/gzrwng096/RH%20Nulo/maxresdefault%20(2).jpg?updatedAt=1751921520460',
    genre: ['Sci-Fi', 'Adventure', 'Drama'],
    rating: 'PG-13',
    releaseYear: 2019,
    featured: true,
    videoUrl: 'https://ik.imagekit.io/gzrwng096/RH%20Nulo/RH%20Nulo.mp4?updatedAt=1751922099564',
    trailerUrl: 'https://www.youtube.com/embed/WSCt0ti_wjs?si=J-REG0IuNy0VL1Fm',
    introStart: 0,
    introEnd: 1,
  },
  {
    id: '2',
    type: 'series',
    title: 'El último segundo',
    description: 'Eric y sus amigos tenían una vida normal hasta que el apocalipsis comenzó. Ahora, Eric, Emily, Dante, Rose, Kevin y Violeta deben sobrevivir en un mundo donde cada segundo cuenta.',
    thumbnailUrl: 'https://ik.imagekit.io/gzrwng096/El%20%C3%BAltimo%20segundo/sddefault%20(7).jpg?updatedAt=1751923615356',
    backdropUrl: 'https://ik.imagekit.io/gzrwng096/El%20%C3%BAltimo%20segundo/sddefault%20(7).jpg?updatedAt=1751923615356',
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    rating: 'R',
    releaseYear: 2020,
    trailerUrl: 'https://youtu.be/ofLMSTKLjVU',
    seasons: [
      {
        id: 's1',
        seasonNumber: 1,
        episodes: [
          {
            id: 's1e1',
            title: 'El Comienzo del Fin',
            description: 'Eric debe cuidar a su hermana pequeña tras el accidente de sus padres, pero el día toma un giro oscuro.',
            thumbnailUrl: 'https://ik.imagekit.io/gzrwng096/El%20%C3%BAltimo%20segundo/sddefault%20(7).jpg?updatedAt=1751923615356',
            videoUrl: 'https://ik.imagekit.io/gzrwng096/Guerra%20de%20amor/Guerra%20de%20____%20_Cap%C3%ADtulo%201_%7BSerie%20original_%7DGacha%20life%20(720p_30fps_H264-128kbit_AAC).mp4?updatedAt=1751918267140',
            duration: '22m',
            introStart: 0,
            introEnd: 64
          },
          {
            id: 's1e2',
            title: 'Supervivientes',
            description: 'El grupo se encuentra por primera vez y decide refugiarse en la escuela.',
            thumbnailUrl: 'https://picsum.photos/seed/s1e2/400/225',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
            duration: '24m'
          },
          {
            id: 's1e3',
            title: 'La Decisión',
            description: 'Sin suministros y rodeados, deben tomar una decisión imposible.',
            thumbnailUrl: 'https://picsum.photos/seed/s1e3/400/225',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            duration: '21m'
          }
        ]
      },
      {
        id: 's2',
        seasonNumber: 2,
        episodes: [
          {
            id: 's2e1',
            title: 'Un Nuevo Mundo',
            description: 'Han pasado dos años. Las reglas han cambiado.',
            thumbnailUrl: 'https://picsum.photos/seed/s2e1/400/225',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
            duration: '25m'
          }
        ]
      }
    ]
  },
  {
    id: '3',
    type: 'movie',
    title: 'Del corazón roto a rompe corazones',
    description: 'Una chica dolida y dispuesta a no confiar más en el amor, logra superar sus miedos gracias a alguien inesperado...',
    thumbnailUrl: 'https://ik.imagekit.io/a2lfezf3h/Del%20coraz%C3%B3n%20roto%20a...%20rompe%20corazones/maxresdefault%20(3).jpg?updatedAt=1751924242363',
    backdropUrl: 'https://ik.imagekit.io/a2lfezf3h/Del%20coraz%C3%B3n%20roto%20a...%20rompe%20corazones/maxresdefault%20(3).jpg?updatedAt=1751924242363',
    genre: ['History', 'Drama', 'Action'],
    rating: 'TV-MA',
    releaseYear: 2020,
    videoUrl: 'https://ik.imagekit.io/a2lfezf3h/Del%20coraz%C3%B3n%20roto%20a...%20rompe%20corazones/Del%20coraz%C3%B3n%20roto%20a...%20rompe%20corazones.mp4?updatedAt=1751924369506',
    trailerUrl: 'https://ik.imagekit.io/a2lfezf3h/Del%20coraz%C3%B3n%20roto%20a...%20rompe%20corazones/Del%20coraz%C3%B3n%20roto%20a...%20rompe%20corazones.mp4?updatedAt=1751924369506',
  },
  {
    id: '4',
    type: 'movie',
    title: '1983',
    description: 'Tanto la música como la trama de la mini pelicula estan inspirados en el Modo 1980 de Yandere Simulator.',
    thumbnailUrl: 'https://ik.imagekit.io/4nltps9rs/1983/sddefault.jpg?updatedAt=1751928743920',
    backdropUrl: 'https://ik.imagekit.io/4nltps9rs/1983/sddefault.jpg?updatedAt=1751928743920',
    genre: ['Horror', 'Mystery', 'Thriller'],
    rating: 'R',
    releaseYear: 2022,
    videoUrl: 'https://ik.imagekit.io/4nltps9rs/1983/_VIEJO__1983_%20Mini%20Pelicula%20de%20Terror_%C2%A6%C2%A6_%20Gacha%20Neon_%C2%A6%C2%A6_Original_%C2%A6%C2%A6__CONTIENE%20SANGRE_%20(480p_30fps_H264-128kbit_AAC).mp4?updatedAt=1751928755930',
    trailerUrl: 'https://ik.imagekit.io/4nltps9rs/1983/_VIEJO__1983_%20Mini%20Pelicula%20de%20Terror_%C2%A6%C2%A6_%20Gacha%20Neon_%C2%A6%C2%A6_Original_%C2%A6%C2%A6__CONTIENE%20SANGRE_%20(480p_30fps_H264-128kbit_AAC).mp4?updatedAt=1751928755930',
  },
  {
    id: '5',
    type: 'movie',
    title: 'Corazón demoniaco',
    description: 'Una chica llamada Naidi es llevada al bosque por un collar sagrado que la elige, y el gigante maldito que debía vigilarla termina enamorándose de ella.',
    thumbnailUrl: 'https://ik.imagekit.io/4nltps9rs/corazon%20demoniaco/sddefault%20(1).jpg?updatedAt=1751928859407',
    backdropUrl: 'https://ik.imagekit.io/4nltps9rs/corazon%20demoniaco/sddefault%20(1).jpg?updatedAt=1751928859407',
    genre: ['Comedy'],
    rating: 'PG-13',
    releaseYear: 2024,
    videoUrl: 'https://ik.imagekit.io/4nltps9rs/corazon%20demoniaco/_Corazon%20demoniaco_mini%20pelicula%20Original%20gacha%20club%20%20%E2%9D%A3%EF%B8%8E%C3%87rist%C3%A5%C5%82is%20%C4%90i%C3%A5m%C3%B8n%C4%91s%E2%9D%A3%EF%B8%8E%20(1080p_30fps_H264-128kbit_AAC).mp4?updatedAt=1751928892173',
    trailerUrl: 'https://ik.imagekit.io/4nltps9rs/corazon%20demoniaco/_Corazon%20demoniaco_mini%20pelicula%20Original%20gacha%20club%20%20%E2%9D%A3%EF%B8%8E%C3%87rist%C3%A5%C5%82is%20%C4%90i%C3%A5m%C3%B8n%C4%91s%E2%9D%A3%EF%B8%8E%20(1080p_30fps_H264-128kbit_AAC).mp4?updatedAt=1751928892173',
  },
  {
    id: '6',
    type: 'movie',
    title: 'Enfermo',
    description: 'este video es una mini pelicula de gacha life en teoria es una versioin retorcida de mi vida je je bueno no importa otra cosa si al principio del video se oye la vos de una mujer es el programa de voz.',
    thumbnailUrl: 'https://ik.imagekit.io/4nltps9rs/enfermo/hqdefault%20(2).jpg?updatedAt=1751929289384',
    backdropUrl: 'https://ik.imagekit.io/4nltps9rs/enfermo/hqdefault%20(2).jpg?updatedAt=1751929289384',
    genre: ['Sci-Fi', 'Horror'],
    rating: 'PG-13',
    releaseYear: 2019,
    videoUrl: 'https://ik.imagekit.io/4nltps9rs/enfermo/enfermo%20mini%20pel%C3%ADcula%20cuddles%20terror%20gacha%20life%20(leer%20descripci%C3%B3n)%20(1080p_30fps_H264-128kbit_AAC).mp4?updatedAt=1751929323701',
    trailerUrl: 'https://ik.imagekit.io/4nltps9rs/enfermo/enfermo%20mini%20pel%C3%ADcula%20cuddles%20terror%20gacha%20life%20(leer%20descripci%C3%B3n)%20(1080p_30fps_H264-128kbit_AAC).mp4?updatedAt=1751929323701',
  },
  {
    id: '7',
    type: 'movie',
    title: 'Amor a primera vista',
    description: 'No description has been added to this video.',
    thumbnailUrl: 'https://ik.imagekit.io/4nltps9rs/Ni%C3%B1ero/maxresdefault%20(1).jpg?updatedAt=1751932881796',
    backdropUrl: 'https://ik.imagekit.io/4nltps9rs/Ni%C3%B1ero/maxresdefault%20(1).jpg?updatedAt=1751932881796',
    genre: ['Drama', 'Romance'],
    rating: 'TV-14',
    releaseYear: 2023,
    videoUrl: 'https://res.cloudinary.com/dfznsof9i/video/upload/v1752007574/Ninero-mini%20pelicula-gacha%20life-yaoi%20sano_leer%20la%20descripcion/Ninero-mini_pelicula_gacha_life_yaoi_sano_leer_la_descripcion_1080p_30fps_H264-128kbit_AAC_gvyyxd.mp4',
    trailerUrl: 'https://res.cloudinary.com/dfznsof9i/video/upload/v1752007574/Ninero-mini%20pelicula-gacha%20life-yaoi%20sano_leer%20la%20descripcion/Ninero-mini_pelicula_gacha_life_yaoi_sano_leer_la_descripcion_1080p_30fps_H264-128kbit_AAC_gvyyxd.mp4',
  },
  {
    id: '8',
    type: 'movie',
    title: 'NUESTRA VERDADERA HISTORIA DE AMOR',
    description: 'En este video especial de la Semana Lyniel les traigo una mini película de Gacha Life animada muy importante para Lyna y Daniel, en la que les cuentan nuestra historia y cómo se conocieron. Si bien está basada en hechos reales, hay algunos detalles que cambian.',
    thumbnailUrl: 'https://ik.imagekit.io/4nltps9rs/NUESTRA%20VERDADERA%20HISTORIA%20DE%20AMOR%20/hqdefault%20(5).jpg?updatedAt=1751932890915',
    backdropUrl: 'https://ik.imagekit.io/4nltps9rs/NUESTRA%20VERDADERA%20HISTORIA%20DE%20AMOR%20/maxresdefault%20(2).jpg?updatedAt=1751932891069',
    genre: ['Action', 'Adventure'],
    rating: 'PG-13',
    releaseYear: 2022,
    videoUrl: 'https://res.cloudinary.com/dfznsof9i/video/upload/v1752007603/NUESTRA_VERDADERA_HISTORIA_DE_AMOR_Mini_Pel%C3%ADcula_Gacha_Life_1080p_50fps_H264-128kbit_AAC_yhpjtw.mp4',
    trailerUrl: 'https://res.cloudinary.com/dfznsof9i/video/upload/v1752007603/NUESTRA_VERDADERA_HISTORIA_DE_AMOR_Mini_Pel%C3%ADcula_Gacha_Life_1080p_50fps_H264-128kbit_AAC_yhpjtw.mp4',
  },
  {
    id: '9',
    type: 'movie',
    title: 'Oxigeno',
    description: `Año 2030. Se declara una emergencia mundial. Todas las plantas dejaron de producir CO2 a causa de la alta contaminación en el ambiente, el fin se parecía acercarse, hasta que unos científicos descubrieron un mineral que poseía las mismas características que el CO2 y que transformada en una sustancia líquida podría ser inyectada en nuestro organismo y nos daba las mismas capacidades para poder vivir. Así fue como esta sustancia fue denominada ''Oxígeno'', un líquido vital para todo ser humano hoy en día en el año 3050. Sin embargo ahora donde nuevamente este recurso escasea y ocurre un gran robo junto a una organización con fines desconocidos, ¿Qué serán de nuestros dos protagonistas cuando les queden pocas opciones de seguir una vida medianamente normal?`,
    thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/e0a88cef-ec2b-42d1-9493-2436c9897975/maxresdefault.jpg',
    backdropUrl: 'https://2qhd7azteo.ucarecd.net/e0a88cef-ec2b-42d1-9493-2436c9897975/maxresdefault.jpg',
    genre: ['Sci-Fi', 'Thriller', 'Mystery'],
    rating: 'R',
    releaseYear: 2021,
    videoUrl: 'https://2qhd7azteo.ucarecd.net/1730bb17-b31f-4308-9a07-f173e6c1d747/OXGENOminipelculaenespaolconvocesGachaClub1080p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://res.cloudinary.com/dozucdr1j/video/upload/v1763420458/Ox%C3%ADgeno_TR%C3%81ILER_AVANCE_mini_pel%C3%ADcula_con_voces_Gacha_Club_1080p_50fps_H264-128kbit_AAC_kfjief.mp4',
  },
  {
    id: '10',
    type: 'movie',
    title: 'Un peligro inminente',
    description: 'A young historian discovers an ancient artifact that predicts the future. She must protect it from a clandestine organization that wants to weaponize its power.',
    thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/b18468cd-3080-4423-8ae9-7b2485328aed/maxresdefault1.jpg',
    backdropUrl: 'https://2qhd7azteo.ucarecd.net/b18468cd-3080-4423-8ae9-7b2485328aed/maxresdefault1.jpg',
    genre: ['Adventure', 'Fantasy', 'Action'],
    rating: 'PG-13',
    releaseYear: 2021,
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
  },
  {
    id: '11',
    type: 'movie',
    title: 'Dentro de casa',
    description: 'Trapped by a blizzard in a remote mountain cabin, a group of strangers discovers that a terrifying creature lurks outside, and the greater danger might be within.',
    thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/456210e4-c342-4d5f-aadd-c9857d04f887/sddefault.jpg',
    backdropUrl: 'https://2qhd7azteo.ucarecd.net/456210e4-c342-4d5f-aadd-c9857d04f887/sddefault.jpg',
    genre: ['Horror', 'Thriller'],
    rating: 'R',
    releaseYear: 2024,
    videoUrl: 'https://2qhd7azteo.ucarecd.net/dea1f289-251e-427d-be4f-f6d424910929/DentrodecasaMiniPelculaORIGINALLeerDescripcin1080p_60fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
  },
  {
    id: '12',
    type: 'movie',
    title: 'Repite despues de mi',
    description: 'A team of deep-sea explorers stumbles upon the lost city of Atlantis, only to awaken its ancient, monstrous guardians.',
    thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/0a93e6f0-9cca-4ff4-87c3-db4b4d71cb5a/hqdefault.jpg',
    backdropUrl: 'https://2qhd7azteo.ucarecd.net/0a93e6f0-9cca-4ff4-87c3-db4b4d71cb5a/hqdefault.jpg',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 'PG-13',
    releaseYear: 2018,
    videoUrl: 'https://2qhd7azteo.ucarecd.net/0cf47aaa-5ec4-42b5-9883-1943bb02fdfd/Repitedespusdemi_MinipelculaConvoces12ORIGINALGachaclubGachalife1080p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://2qhd7azteo.ucarecd.net/0cf47aaa-5ec4-42b5-9883-1943bb02fdfd/Repitedespusdemi_MinipelculaConvoces12ORIGINALGachaclubGachalife1080p_30fps_H264128kbit_AAC.mp4',
  },
  {
    id: '13',
    type: 'movie',
    title: 'Repite despues de mi 2',
    description: 'A cynical musician finds a vintage vinyl record that allows her to travel back in time, but every trip alters her present in heartbreaking ways.',
    thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/04750149-39f9-4745-aea6-7298748522c4/maxresdefault2.jpg',
    backdropUrl: 'https://2qhd7azteo.ucarecd.net/04750149-39f9-4745-aea6-7298748522c4/maxresdefault2.jpg',
    genre: ['Drama', 'Romance', 'Fantasy'],
    rating: 'PG-13',
    releaseYear: 2022,
    videoUrl: 'https://res.cloudinary.com/dozucdr1j/video/upload/v1763420730/Repite_despu%C3%A9s_de_mi2%EF%B8%8F%E2%83%A3___Mini_pel%C3%ADcula_Original___Con_voces_2_2_LEER_DESCRIPCI%C3%93N_1080p_30fps_H264-128kbit_AAC_ttub4i.mp4',
    trailerUrl: 'https://res.cloudinary.com/dozucdr1j/video/upload/v1763420730/Repite_despu%C3%A9s_de_mi2%EF%B8%8F%E2%83%A3___Mini_pel%C3%ADcula_Original___Con_voces_2_2_LEER_DESCRIPCI%C3%93N_1080p_30fps_H264-128kbit_AAC_ttub4i.mp4',
  },
  {
    id: '14',
    type: 'movie',
    title: 'mi bully es el padre de mi hijo',
    description: 'In 1920s New York, a young woman from a poor neighborhood gets entangled in the dangerous and deceptive world of the city\'s high society.',
    thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/622ff849-7dda-4722-b6cf-fba2fb0a78a9/maxresdefault3.jpg',
    backdropUrl: 'https://2qhd7azteo.ucarecd.net/622ff849-7dda-4722-b6cf-fba2fb0a78a9/maxresdefault3.jpg',
    genre: ['Drama', 'History', 'Romance'],
    rating: 'TV-14',
    releaseYear: 2020,
    videoUrl: 'https://2qhd7azteo.ucarecd.net/bda68e6e-5334-4c1f-a539-787eb0f33b5b/MIBULLYESELPADREDEMIHIJOGachalifeminipelculaGLMM1440p_30fps_AV1128kbit_AAC.mp4',
    trailerUrl: 'https://2qhd7azteo.ucarecd.net/bda68e6e-5334-4c1f-a539-787eb0f33b5b/MIBULLYESELPADREDEMIHIJOGachalifeminipelculaGLMM1440p_30fps_AV1128kbit_AAC.mp4',
  },
  {
    id: '15',
    type: 'movie',
    title: 'En proceso',
    description: 'The first zero-gravity sports tournament is sabotaged. An underdog team of misfits must uncover the conspiracy before the final match.',
    thumbnailUrl: 'https://picsum.photos/seed/zero1/400/6600',
    backdropUrl: 'https://picsum.photos/seed/zero2/1920/108530',
    genre: ['Comedy', 'Sci-Fi', 'Action'],
    rating: 'PG',
    releaseYear: 2025,
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  },
  {
    id: '16',
    type: 'series',
    title: 'El mundo alocado de Lucy',
    description: 'Mundo loco de Lucy 797',
    thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/83a8b8fe-190c-4018-b35c-3c830c7aefe7/LamudanzaelcomienzodeunanuevaaventuraCaptulo1Lucy797BQ.jpg',
    backdropUrl: 'https://2qhd7azteo.ucarecd.net/83a8b8fe-190c-4018-b35c-3c830c7aefe7/LamudanzaelcomienzodeunanuevaaventuraCaptulo1Lucy797BQ.jpg',
    genre: ['Sci-Fi', 'Fantasy', 'Adventure'],
    rating: 'TV-14',
    releaseYear: 2025,
    seasons: [
      {
        id: 's1',
        seasonNumber: 1,
        episodes: [
          {
            id: 's1e1',
            title: ' La mudanza, el comienzo de una nueva aventura',
            description: 'Holaa hermosos y hermosas 💗 hoy vengo con el primer capítulo de la serie espero les guste mucho, aprovecho para decir que apartir de ahora comenzaré a saludar en los próximos videos✨🌺',
            thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/83a8b8fe-190c-4018-b35c-3c830c7aefe7/LamudanzaelcomienzodeunanuevaaventuraCaptulo1Lucy797BQ.jpg',
            videoUrl: 'https://2qhd7azteo.ucarecd.net/99fe03c8-48b4-47ab-9e11-20b959fb4377/LamudanzaelcomienzodeunanuevaaventuraCaptulo1Lucy7971440p_30fps_VP9128kbit_AAC.mkv',
            duration: '5m',
            introStart: 0,
            introEnd: 97
          },
          {
            id: 's1e2',
            title: '24 horas convertida en flewin',
            description: 'Hola chicos :D Por favor mil disculpas por no subir el cap🙏😖 Es que tuve muchos inconvenientes y hoy mismo fué que lo pude terminar🥺💔 Espero me entiendan :3',
            thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/91d6a715-ae9e-4bc2-b68c-2d11a808c1c3/24horasconvertidaenflewinCaptulo2Lucy797BQ.jpg',
            videoUrl: 'https://2qhd7azteo.ucarecd.net/a1dc6113-5be3-4638-939c-f2f4a77f7e30/24horasconvertidaenflewinCaptulo2Lucy7971440p_30fps_VP9128kbit_AAC.mkv',
            duration: '7m',
            introStart: 0,
            introEnd: 97
          },
          {
            id: 's1e3',
            title: 'Nuestro 1er día de clases + nuevos compañeros',
            description: 'Hoy vengo con el capítulo 3 de la serie 🙈💞 Disfrútenlo mucho :D',
            thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/45e751a7-04a3-4730-bfe2-fdbfe31c66ee/Nuestro1erdadeclasesnuevoscompaerosCaptulo3Lucy797BQ.jpg',
            videoUrl: 'https://2qhd7azteo.ucarecd.net/33a14e71-54fc-498e-83a8-6eed4ae998eb/Nuestro1erdadeclasesnuevoscompaerosCaptulo3Lucy7971440p_30fps_VP9128kbit_AAC.mkv',
            duration: '8m'
          },
          {
            id: 's1e4',
            title: 'Descubro que tengo un hermano',
            description: 'ADVERTENCIA: A partir de ahora yo seré la voz de Jack (Aún no sé si temporal o definitivo), debido a que la persona que hacía su voz se encontraba inactivo, tuve que hacer la voz lo más parecido posible',
            thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/4a25f82e-2595-457b-960b-2529730f8a8f/DescubroquetengounhermanoCaptulo4Colaboracinconxtoxin4343Lucy797BQ.jpg',
            videoUrl: 'https://2qhd7azteo.ucarecd.net/f8ec456e-d117-46d8-82d8-ae9a2c887d74/DescubroquetengounhermanoCaptulo4Colaboracinconxtoxin4343Lucy7971440p_30fps_VP9128kbit_AAC.mkv',
            duration: '8m'
          },
          {
            id: 's1e5',
            title: 'Encerrados en el baño de profesores',
            description: `Hoy les traigo el capítulo 5 de la serie. Recuerden que habrá una nueva intro, aunque pido mil disculpas si les gustaba más la anterior 🥺. Pero aún así espero lo disfruten 💞.`,
            thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/36e0d801-ce9e-464c-94d7-225f0e78e760/EncerradosenelbaodeprofesoresNuevaintroLucy797BQ.jpg',
            videoUrl: 'https://2qhd7azteo.ucarecd.net/10743af3-679e-48b1-9cfd-a8fe5b70cb99/EncerradosenelbaodeprofesoresNuevaintroLucy7971440p_30fps_VP9128kbit_AACespaol.mkv',
            duration: '11m'
          },
          {
            id: 's1e6',
            title: 'Una navidad inolvidable',
            description: `Hola chicos, este es el especial navideño 🎄💐 Espero que lo disfrurten mucho :3
Hubo un fragmento que tuve que elminar porque mi cel no tenía espacio, pero lo subiré después 😊💕`,
            thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/247d9b57-d272-443c-9d54-109cfb040270/UnanavidadinolvidableEspecialnavideoConundadeatrasovHikalucyLucy797BQ.jpg',
            videoUrl: 'https://2qhd7azteo.ucarecd.net/65fefd4b-9b3e-4628-8d23-01e4684bf46e/UnanavidadinolvidableEspecialnavideoConundadeatrasovHikalucyLucy797720p_30fps_H264128kbit_AAC.mp4',
            duration: '13m'
          },
          {
            id: 's1e7',
            title: '¡Preguntas y Retos!',
            description: 'Solo preguntas y retos.',
            thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/7955d340-b78a-4867-b1a5-3360c5f1f4b6/PreguntasyRetosConlacreadoravLucy797BQ.jpg',
            videoUrl: 'https://2qhd7azteo.ucarecd.net/8d6355bd-bd75-48ec-8366-0f8a2f5f803a/PreguntasyRetosConlacreadoravLucy7971440p_30fps_VP9128kbit_AAC.mkv',
            duration: '10m'
          },
          {
            id: 's1e8',
            title: 'Visitamos a Alex + poniendo celoso a Hikari',
            description: 'Aquí les traigo el cap de la serie, enserio lo siento por haberme tardado muchísimo 😿, últimamente tuve falta de motivación y ya saben, la escuela jsjs ^^ 😅.',
            thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/7c650308-3a84-4d77-a093-b0848d3ba96b/VisitamosaAlexponiendocelosoaHikariCaptulo8Lucy797BQ.jpg',
            videoUrl: 'https://2qhd7azteo.ucarecd.net/bf287f8a-c5eb-48e0-91b2-82f76088db3a/VisitamosaAlexponiendocelosoaHikariCaptulo8Lucy7971440p_30fps_VP9128kbit_AAC.mkv',
            duration: '11m'
          },
          {
            id: 's1e9',
            title: 'Jack confiesa que le gusta Anita ¿Sale mal?',
            description: `Espero que les haya gustado, tmb hay nuevas voces para algunos personajes 😽, nuevamente pido disculpas por tardarme como 2 meses en subirlo jsjs, pero weno, pido perdón tmb si hubieron algunos errores de edición :')`,
            thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/c3336c12-3363-462f-8ba7-10cd41c13be7/JackconfiesaquelegustaAnitaSalemalNuevosvillanosymsCaptulo9CONVOCESHQ.jpg',
            videoUrl: 'https://2qhd7azteo.ucarecd.net/234e2bad-d424-4a98-ab4f-0d922b201b43/JackconfiesaquelegustaAnitaSalemalNuevosvillanosymsCaptulo9CONVOCES1440p_30fps_VP9128kbit_AAC.mkv',
            duration: '19m'
          },
          {
            id: 's1e10',
            title: 'Si yo estuviera en una escuela de chicos',
            description: `Espero les guste florecitas y capullitos 🥰. Felices fiestas a ustedes, pásenla lindo 💓.
Lamento haberme tardado en subirlo nuevamente, esta vez tuve problemas con el micrófono, por eso escucharán algunos audios de Lucy un poco saturados o algo así :').`,
            thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/81296ab3-b3df-4eeb-bac4-d0031f24aa3f/SiyoestuvieraenunaescueladechicosConvocesCaptulo10Lucy797BQ.jpg',
            videoUrl: 'https://2qhd7azteo.ucarecd.net/6de6bf38-f05d-478c-8bf7-871443ed97e4/SiyoestuvieraenunaescueladechicosConvocesCaptulo10Lucy7971440p_30fps_VP9128kbit_AAC.mkv',
            duration: '12m'
          },
          {
            id: 's1e11',
            title: 'La ex de Alfredo',
            description: 'Espero les guste, lo siento la tardanza de casi 7 meses, pero como dicen, más vale tarde que nunca, igualmente me disculpo x los errores que podrían haber ya sea de edición o diálogo :\').',
            thumbnailUrl: 'https://2qhd7azteo.ucarecd.net/94e2cc05-196c-4ccd-bade-61b7fa80f998/LaexdeAlfredoNuevospersonajesLucy797LaserieCaptulo11BQ.jpg',
            videoUrl: 'https://2qhd7azteo.ucarecd.net/42653f68-f000-427a-9d28-de9558dc2b2d/LaexdeAlfredoNuevospersonajesLucy797LaserieCaptulo111080p_30fps_H264128kbit_AAC.mp4',
            duration: '23m'
          },
          {
            id: 's1e12',
            title: 'Las nuevas mascotas (Parte 1/2)',
            description: 'Sin descripcion.',
            thumbnailUrl: 'https://602td9md5u.ucarecd.net/7a9bd90b-7c6d-4061-858a-a0a53eec7f86/maxresdefault.jpg',
            videoUrl: 'https://602td9md5u.ucarecd.net/e51e9041-198a-4d75-aad0-6f607b2889d5/TheNewPetsPart12Chapter12LucysCrazyWorld1080p_30fps_H264128kbit_AAC.mp4',
            duration: '15m'
          }
        ]
      }
    ]
  },
  {
    id: '17',
    type: 'movie',
    title: 'Bandos distintos',
    description: 'Puse la advertencia por si acaso, ya que no quiero que me funen innecesariamente...de todas formas recuerden que es FICCIÓN y nada de esto es real, solo son muñecos que se pueden manipular a gusto! dicho esto disfruten',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/115d2c13-ca55-44ab-9d71-d4eb238aae82/brendaDemonMinipeliculasgachalife_2.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/115d2c13-ca55-44ab-9d71-d4eb238aae82/brendaDemonMinipeliculasgachalife_2.jpg',
    genre: ['Sci-Fi', 'Thriller'],
    rating: 'PG-13',
    releaseYear: 2022,
    videoUrl: 'https://57zt5wokny.ucarecd.net/9cb6c838-c978-4928-aa0d-71259bd8701d/BandosdistintosglygcminipeliLayla_studiogachagachalifeminiature576p_25fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/9cb6c838-c978-4928-aa0d-71259bd8701d/BandosdistintosglygcminipeliLayla_studiogachagachalifeminiature576p_25fps_H264128kbit_AAC.mp4',
  },
  {
    id: '18',
    type: 'movie',
    title: 'DEL ODIO AL AMOR',
    description: 'Que flojera',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/bd10f018-5938-4186-b711-b710de2af4ed/PelculaDELODIOALAMORGachaLifeImMichelleInspiradoenDimarcy21BQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/bd10f018-5938-4186-b711-b710de2af4ed/PelculaDELODIOALAMORGachaLifeImMichelleInspiradoenDimarcy21BQ.jpg',
    genre: ['Drama', 'Romance', 'Music'],
    rating: 'R',
    releaseYear: 2021,
    videoUrl: 'https://57zt5wokny.ucarecd.net/d89c6594-2d86-4f0b-b675-86eceb38634e/PelculaDELODIOALAMORGachaLifeImMichelleInspiradoenDimarcy211080p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/d89c6594-2d86-4f0b-b675-86eceb38634e/PelculaDELODIOALAMORGachaLifeImMichelleInspiradoenDimarcy211080p_30fps_H264128kbit_AAC.mp4',
  },
  {
    id: '19',
    type: 'movie',
    title: 'Un Regalo para NAVIDAD',
    description: 'Feliz navidad adelantada ',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/33f76c0e-7960-4d6b-89bc-8ff0f3b80a8d/UnRegaloparaNAVIDADMiniPeliOriginalPasadodeMaxItsMagalyHQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/33f76c0e-7960-4d6b-89bc-8ff0f3b80a8d/UnRegaloparaNAVIDADMiniPeliOriginalPasadodeMaxItsMagalyHQ.jpg',
    genre: ['Action', 'Sci-Fi'],
    rating: 'R',
    releaseYear: 2024,
    videoUrl: 'https://57zt5wokny.ucarecd.net/e00e260d-3811-429a-80fe-9de067e2863a/UnRegaloparaNAVIDADMiniPeliOriginalPasadodeMaxItsMagaly720p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/e00e260d-3811-429a-80fe-9de067e2863a/UnRegaloparaNAVIDADMiniPeliOriginalPasadodeMaxItsMagaly720p_30fps_H264128kbit_AAC.mp4',
  },
  {
    id: '20',
    type: 'movie',
    title: 'LA MAFIA Y LA REALEZA',
    description: 'La mafia y la realza: Dicen que "los opuestos se atraen" no? Pues dile eso a un mafioso y una princesa!',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/3753403b-213b-4df8-a4f5-3af6a30840f1/LAMAFIAYLAREALEZAGachalifeminipelculaGLMMBQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/3753403b-213b-4df8-a4f5-3af6a30840f1/LAMAFIAYLAREALEZAGachalifeminipelculaGLMMBQ.jpg',
    genre: ['Adventure', 'Action'],
    rating: 'PG',
    releaseYear: 2021,
    videoUrl: 'https://57zt5wokny.ucarecd.net/a5575b24-a783-4884-bd99-dc1c1bde81fe/LAMAFIAYLAREALEZAGachalifeminipelculaGLMM1080p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/a5575b24-a783-4884-bd99-dc1c1bde81fe/LAMAFIAYLAREALEZAGachalifeminipelculaGLMM1080p_30fps_H264128kbit_AAC.mp4',
  },
  {
    id: '21',
    type: 'movie',
    title: 'Que hay en mi corazón♡?',
    description: 'Hola somos 🌼Cheng Hua🌼, esperamos que les haya gustado esta Mini Pelicula:D, nos tomo un tiempo hacerla💦 [literal como mitad de año], pero igual queremos que la disfruten esta echa con mucho cariño (y una pizca de pndejadas) SUSCRIBANSEEฅ^•ﻌ•^ฅ',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/34caadc9-0ab1-4169-9924-a61f47768e86/QuehayenmicoraznMiniPeliculaGachaYaoiBLChengHuaBQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/34caadc9-0ab1-4169-9924-a61f47768e86/QuehayenmicoraznMiniPeliculaGachaYaoiBLChengHuaBQ.jpg',
    genre: ['Horror', 'Thriller'],
    rating: 'R',
    releaseYear: 2022,
    videoUrl: 'https://57zt5wokny.ucarecd.net/74110c76-d94b-4cba-ada9-84d1f19f4b59/QuehayenmicoraznMiniPeliculaGachaYaoiBLChengHua1080p_50fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/74110c76-d94b-4cba-ada9-84d1f19f4b59/QuehayenmicoraznMiniPeliculaGachaYaoiBLChengHua1080p_50fps_H264128kbit_AAC.mp4',
  },
  {
    id: '22',
    type: 'movie',
    title: 'Hecho Realidad',
    description: 'no se',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/0b6a7f6c-e2f6-4534-ab9e-76a9f98322b9/HechoRealidadMinipeliculaBLYaoiSanoGayGachaClubBQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/0b6a7f6c-e2f6-4534-ab9e-76a9f98322b9/HechoRealidadMinipeliculaBLYaoiSanoGayGachaClubBQ.jpg',
    genre: ['Romance', 'Comedy'],
    rating: 'PG-13',
    releaseYear: 2020,
    videoUrl: 'https://57zt5wokny.ucarecd.net/0ccddec7-8818-4f69-ba67-5ff9fa5d0d4e/HechoRealidadMinipeliculaBLYaoiSanoGayGachaClub1080p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/0ccddec7-8818-4f69-ba67-5ff9fa5d0d4e/HechoRealidadMinipeliculaBLYaoiSanoGayGachaClub1080p_30fps_H264128kbit_AAC.mp4',
  },
  {
    id: '23',
    type: 'movie',
    title: 'EL CRIMINAL Y LA PRINCESA',
    description: 'JAJAJAJAJ',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/6f979457-5768-4005-b896-10720f7509fe/ELCRIMINALYLAPRINCESAMinipeliOriginalMiniaturainspiradagiuliamodoneseHQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/6f979457-5768-4005-b896-10720f7509fe/ELCRIMINALYLAPRINCESAMinipeliOriginalMiniaturainspiradagiuliamodoneseHQ.jpg',
    genre: ['Sci-Fi', 'Action', 'Crime'],
    rating: 'PG-13',
    releaseYear: 2022,
    videoUrl: 'https://57zt5wokny.ucarecd.net/2f164d16-20f2-4900-be5b-1ef722503acc/ELCRIMINALYLAPRINCESAMinipeliOriginalMiniaturainspiradagiuliamodonese720p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/2f164d16-20f2-4900-be5b-1ef722503acc/ELCRIMINALYLAPRINCESAMinipeliOriginalMiniaturainspiradagiuliamodonese720p_30fps_H264128kbit_AAC.mp4',
  },
  {
    id: '24',
    type: 'movie',
    title: 'CADENAS DE AMOR',
    description: 'MUAJAJAJAJJA',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/531b7d27-579a-47f5-a4e2-c9137ea2efef/CADENASDEAMORAlumnosnuevosCelosGachalifeHQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/531b7d27-579a-47f5-a4e2-c9137ea2efef/CADENASDEAMORAlumnosnuevosCelosGachalifeHQ.jpg',
    genre: ['Fantasy', 'Family', 'Adventure'],
    rating: 'PG',
    releaseYear: 2021,
    videoUrl: 'https://57zt5wokny.ucarecd.net/bf02ed52-2348-48f8-b826-9784cf9a15af/CADENASDEAMORAlumnosnuevosCelosGachalife720p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/bf02ed52-2348-48f8-b826-9784cf9a15af/CADENASDEAMORAlumnosnuevosCelosGachalife720p_30fps_H264128kbit_AAC.mp4',
  },
  {
    id: '25',
    type: 'movie',
    title: '𝕯𝖊 𝖊́𝖕𝖔𝖈𝖆𝖘 𝖉𝖎𝖘𝖙𝖎𝖓𝖙𝖆𝖘',
    description: 'De épocas distintas: La típica adolescente que no presta atención a los estudios pero que en tan solo un día, su vida dió muchas vueltas, llevandola a una nueva realidad...',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/5347c81b-8f3e-4649-82fb-6b2f8159df42/GachalifeMiniPelculaGLMMOriginalBQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/5347c81b-8f3e-4649-82fb-6b2f8159df42/GachalifeMiniPelculaGLMMOriginalBQ.jpg',
    genre: ['Crime', 'Mystery', 'Drama'],
    rating: 'R',
    releaseYear: 2018,
    videoUrl: 'https://57zt5wokny.ucarecd.net/d4fa0c2d-7002-40f8-b98f-58fd4825ba9e/GachalifeMiniPelculaGLMMOriginal2160p_30fps_VP9128kbit_AAC.mkv',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/d4fa0c2d-7002-40f8-b98f-58fd4825ba9e/GachalifeMiniPelculaGLMMOriginal2160p_30fps_VP9128kbit_AAC.mkv',
  },
  {
    id: '26',
    type: 'movie',
    title: 'YO JAMAS TE OLVIDE',
    description: 'créditos al creador llamado Eduador ',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/a1f6289e-3364-4eb6-bc58-8b121732bb90/YOJAMASTEOLVIDEtemporadacompletaHQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/a1f6289e-3364-4eb6-bc58-8b121732bb90/YOJAMASTEOLVIDEtemporadacompletaHQ.jpg',
    genre: ['Action', 'Crime'],
    rating: 'PG-13',
    releaseYear: 2022,
    videoUrl: 'https://57zt5wokny.ucarecd.net/889f2e6d-b22d-4cf8-87be-5957eec05895/YOJAMASTEOLVIDEtemporadacompleta1080p_30fps_AV1128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/889f2e6d-b22d-4cf8-87be-5957eec05895/YOJAMASTEOLVIDEtemporadacompleta1080p_30fps_AV1128kbit_AAC.mp4',
  },
  {
    id: '27',
    type: 'movie',
    title: 'Mi chico malo',
    description: 'No se agregó una descripción a este video.',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/dae9a3a6-31e7-41d1-8dcf-709d98a2e4db/MichicomaloMinipeligachalifeNOORIGINALHQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/dae9a3a6-31e7-41d1-8dcf-709d98a2e4db/MichicomaloMinipeligachalifeNOORIGINALHQ.jpg',
    genre: ['Romance', 'Fantasy'],
    rating: 'PG-13',
    releaseYear: 2022,
    videoUrl: 'https://57zt5wokny.ucarecd.net/2d99bc27-23c0-4861-a83d-c8f0822c59ba/MichicomaloMinipeligachalifeNOORIGINAL720p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/2d99bc27-23c0-4861-a83d-c8f0822c59ba/MichicomaloMinipeligachalifeNOORIGINAL720p_30fps_H264128kbit_AAC.mp4',
  },
  {
    id: '28',
    type: 'movie',
    title: 'Amor de Cupido',
    description: 'No se agregó una descripción a este video.',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/56c10d63-0f84-45ef-979e-130eabc3bec8/AmordeCupidoMiniPeliGachaClubOriginalMikieStudiosHQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/56c10d63-0f84-45ef-979e-130eabc3bec8/AmordeCupidoMiniPeliGachaClubOriginalMikieStudiosHQ.jpg',
    genre: ['Romance', 'Fantasy'],
    rating: 'PG-13',
    releaseYear: 2022,
    videoUrl: 'https://57zt5wokny.ucarecd.net/b3aed2ec-fc53-4a0c-8564-4197837aa47a/AmordeCupidoMiniPeliGachaClubOriginalMikieStudios1058p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/b3aed2ec-fc53-4a0c-8564-4197837aa47a/AmordeCupidoMiniPeliGachaClubOriginalMikieStudios1058p_30fps_H264128kbit_AAC.mp4',
  },
  {
    id: '29',
    type: 'movie',
    title: 'Desde pequeños...',
    description: 'Una pelicula',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/1dc3eb6c-2f38-413d-9eae-5fdc1abf6c08/DesdepequeosIMiniPeliculaIStarTimeIOriginalBQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/1dc3eb6c-2f38-413d-9eae-5fdc1abf6c08/DesdepequeosIMiniPeliculaIStarTimeIOriginalBQ.jpg',
    genre: ['Drama'],
    rating: 'PG-13',
    releaseYear: 2022,
    videoUrl: 'https://57zt5wokny.ucarecd.net/f5d20930-a148-4a7d-a340-0a783323c75c/DesdepequeosIMiniPeliculaIStarTimeIOriginal1080p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/f5d20930-a148-4a7d-a340-0a783323c75c/DesdepequeosIMiniPeliculaIStarTimeIOriginal1080p_30fps_H264128kbit_AAC.mp4',
  },
  {
    id: '30',
    type: 'movie',
    title: 'Desde pequeños... 2',
    description: 'Secuela',
    thumbnailUrl: 'https://57zt5wokny.ucarecd.net/86db519e-024b-4908-b2a6-f27ebf1ea4d9/Desdepequeos2IMiniPeliculaIStarTimeBQ.jpg',
    backdropUrl: 'https://57zt5wokny.ucarecd.net/86db519e-024b-4908-b2a6-f27ebf1ea4d9/Desdepequeos2IMiniPeliculaIStarTimeBQ.jpg',
    genre: ['Drama'],
    rating: 'PG-13',
    releaseYear: 2022,
    videoUrl: 'https://57zt5wokny.ucarecd.net/8080efe2-ff01-4827-a023-b8b539b019a2/Desdepequeos2IMiniPeliculaIStarTime1080p_30fps_H264128kbit_AAC.mp4',
    trailerUrl: 'https://57zt5wokny.ucarecd.net/8080efe2-ff01-4827-a023-b8b539b019a2/Desdepequeos2IMiniPeliculaIStarTime1080p_30fps_H264128kbit_AAC.mp4',
  }
];

export const LANGUAGES = [
    { code: 'en', name: 'English' },
    { code: 'es-419', name: 'Español Latino' },
    { code: 'es', name: 'Español' },
    { code: 'ja', name: 'Japanese' },
    { code: 'ar', name: 'Arabic' },
    { code: 'pt', name: 'Portuguese' },
    { code: 'fi', name: 'Finnish' },
    { code: 'fr', name: 'French' },
    { code: 'it', name: 'Italian' },
    { code: 'ru', name: 'Russian' },
    { code: 'es-US', name: 'Spanish (United States)' },
    { code: 'pl', name: 'Polish' },
    { code: 'de', name: 'German' },
    { code: 'ko', name: 'Korean' },
    { code: 'ca', name: 'Catalan' },
    { code: 'zu', name: 'Zulu' },
    { code: 'tr', name: 'Turkish' },
    { code: 'zh-CN', name: 'Chinese (China)' },
    { code: 'hi', name: 'Hindi' },
    { code: 'id', name: 'Indonesian' },
    { code: 'ro', name: 'Romanian' },
    { code: 'af', name: 'Afrikaans' },
    { code: 'sq', name: 'Albanian' },
    { code: 'am', name: 'Amharic' },
    { code: 'hy', name: 'Armenian' },
    { code: 'as', name: 'Assamese' },
    { code: 'bn', name: 'Bangla' },
    { code: 'be', name: 'Belarusian' },
    { code: 'my', name: 'Burmese' },
    { code: 'bs', name: 'Bosnian' },
    { code: 'bg', name: 'Bulgarian' },
    { code: 'kn', name: 'Kannada' },
    { code: 'cs', name: 'Czech' },
    { code: 'hr', name: 'Croatian' },
    { code: 'si', name: 'Sinhala' },
    { code: 'da', name: 'Danish' },
    { code: 'sk', name: 'Slovak' },
    { code: 'sl', name: 'Slovenian' },
    { code: 'fil', name: 'Filipino' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
    'en': {
        home: 'Home',
        movies: 'Movies',
        creators: 'Creators',
        myList: 'My List',
        calls: 'Community',
        minigames: 'Minigames',
        searchPlaceholder: 'Search...',
        play: 'Play',
        moreInfo: 'More Info',
        allMovies: 'All Movies',
        searchResults: 'Search Results',
        resultsFor: 'Results for',
        noMatches: 'No matches found for',
        title: 'Title',
        type: 'Type',
        description: 'Description',
        genre: 'Genre (Comma separated)',
        videoUrl: 'Video URL',
        thumbnailUrl: 'Thumbnail URL',
        joinCommunity: 'Join the community',
        copyright: "Copyright © 2025 - 2025 SeikoTV. 'SeikoTV', the SeikoTV logos and name belong to SeikoTV.",
        playTrailer: 'Play Trailer',
        playMovie: 'Play Movie',
        playEpisode: 'Play Episode',
        episodes: 'Episodes',
        genres: 'Genres',
        movie: 'Movie',
        series: 'Series',
        addToList: 'Add to List',
        removeFromList: 'Remove from List',
        emptyWatchlist: 'Your watchlist is empty.',
        joinCall: 'Join Room',
        roomName: 'Room Name',
        enterRoomName: 'Enter a room name (e.g. SeikoFans)',
        displayName: 'Your Name',
        enterDisplayName: 'Enter your display name',
        callsDescription: 'Create or join a free video call room to chat with other fans!',
        recommendedForYou: 'Recommended For You',
        continueWatching: 'Continue Watching',
        changelog: 'Update Notes',
        close: 'Close',
        changelogTitle: 'What\'s New in SeikoTV',
        skipIntro: 'Skip Intro',
        nextEpisode: 'Next Episode',
        generatingRecommendations: 'Generating Personal Picks...',
        genresLabel: 'Genres:',
        releaseLabel: 'Release:',
        ratingLabel: 'Rating:',
        exit: 'Exit',
        donate: 'Donate :)',
        clearHistory: 'Clear History',
        searchHistory: 'Search History',
        privacyPolicy: 'Privacy Policy',
        termsOfService: 'Terms of Service',
        aboutUs: 'About SeikoTV',
        aboutText1: 'SeikoTV is a leading video streaming platform dedicated to bringing you the best in entertainment. From gripping dramas and hilarious comedies to action-packed adventures, our curated library offers something for everyone.',
        aboutText2: 'We are committed to supporting creators and providing a space for unique voices to be heard. Join our community today and discover your next favorite series or movie.',
        quality: 'Quality',
        auto: 'Auto',
        audio: 'Audio',
        subtitles: 'Subtitles',
        off: 'Off',
        settings: 'Settings',
        speed: 'Speed',
        autoPlay: 'Auto Play',
        nextEpisodeIn: 'Next episode in',
        cancel: 'Cancel',
        playNow: 'Play Now',
        minigamesTitle: 'Arcade Zone',
        minigamesDesc: 'Take a break and play some awesome minigames!',
        playGame: 'Play Game',
        comingSoon: 'Coming Soon',
        dataSaver: 'Data Saver',
        spatialAudio: 'Spatial Audio',
        spatialAudioDesc: 'Immersive 3D sound',
        secretGenre1: 'Sci-Fi Anime',
        secretGenre2: 'Biographical Docs',
        secretGenre3: 'B-Horror',
        secretUnlocked: 'Secret Genre Unlocked!'
    },
    'es-419': {
        home: 'Inicio',
        movies: 'Películas',
        creators: 'Creadores',
        myList: 'Mi Lista',
        calls: 'Comunidad',
        minigames: 'Minijuegos',
        searchPlaceholder: 'Buscar...',
        play: 'Reproducir',
        moreInfo: 'Más Info',
        allMovies: 'Todas las Películas',
        searchResults: 'Resultados de Búsqueda',
        resultsFor: 'Resultados para',
        noMatches: 'No se encontraron coincidencias para',
        title: 'Título',
        type: 'Tipo',
        description: 'Descripción',
        genre: 'Género (Separado por comas)',
        videoUrl: 'URL del Video',
        thumbnailUrl: 'URL de la Miniatura',
        joinCommunity: 'Únete a la comunidad',
        copyright: "Copyright © 2025 - 2025 SeikoTV. 'SeikoTV', los logotipos de SeikoTV y el nombre pertenecen a SeikoTV.",
        playTrailer: 'Ver Tráiler',
        playMovie: 'Ver Película',
        playEpisode: 'Ver Episodio',
        episodes: 'Episodios',
        genres: 'Géneros',
        movie: 'Película',
        series: 'Serie',
        addToList: 'Agregar a mi lista',
        removeFromList: 'Quitar de mi lista',
        emptyWatchlist: 'Tu lista está vacía.',
        joinCall: 'Unirse a la Sala',
        roomName: 'Nombre de Sala',
        enterRoomName: 'Ej. FansDeSeiko',
        displayName: 'Tu Nombre',
        enterDisplayName: 'Pon tu nombre visible',
        callsDescription: '¡Crea o únete a una sala de videollamada gratis para charlar con otros fans!',
        recommendedForYou: 'Recomendado para ti',
        continueWatching: 'Continuar viendo',
        changelog: 'Notas de actualización',
        close: 'Cerrar',
        changelogTitle: 'Novedades en SeikoTV',
        skipIntro: 'Saltar Intro',
        nextEpisode: 'Siguiente Episodio',
        generatingRecommendations: 'Generando recomendaciones...',
        genresLabel: 'Géneros:',
        releaseLabel: 'Lanzamiento:',
        ratingLabel: 'Clasificación:',
        exit: 'Salir',
        donate: 'Dóname :)',
        clearHistory: 'Borrar Historial',
        searchHistory: 'Historial de Búsqueda',
        privacyPolicy: 'Política de Privacidad',
        termsOfService: 'Términos de Servicio',
        aboutUs: 'Sobre SeikoTV',
        aboutText1: 'SeikoTV es una plataforma líder de transmisión de video dedicada a brindarte lo mejor en entretenimiento. Desde dramas apasionantes y comedias divertidas hasta aventuras llenas de acción, nuestra biblioteca seleccionada ofrece algo para todos.',
        aboutText2: 'Estamos comprometidos a apoyar a los creadores y proporcionar un espacio para que se escuchen voces únicas. Únete a nuestra comunidad hoy y descubre tu próxima serie o película favorita.',
        quality: 'Calidad',
        auto: 'Automática',
        audio: 'Audio',
        subtitles: 'Subtítulos',
        off: 'Desactivado',
        settings: 'Configuración',
        speed: 'Velocidad',
        autoPlay: 'Reproducción Automática',
        nextEpisodeIn: 'Siguiente episodio en',
        cancel: 'Cancelar',
        playNow: 'Reproducir Ahora',
        minigamesTitle: 'Zona Arcade',
        minigamesDesc: '¡Tómate un descanso y juega algunos minijuegos increíbles!',
        playGame: 'Jugar',
        comingSoon: 'Próximamente',
        dataSaver: 'Modo Ahorro',
        spatialAudio: 'Audio Espacial',
        spatialAudioDesc: 'Sonido 3D inmersivo',
        secretGenre1: 'Anime Ciencia Ficción',
        secretGenre2: 'Documentales Bio',
        secretGenre3: 'Terror Serie B',
        secretUnlocked: '¡Género Secreto Desbloqueado!'
    },
    'ja': {
        home: 'ホーム',
        movies: '映画',
        creators: 'クリエイター',
        myList: 'マイリスト',
        calls: 'コミュニティ',
        minigames: 'ミニゲーム',
        searchPlaceholder: '検索...',
        play: '再生',
        moreInfo: '詳細',
        allMovies: 'すべての映画',
        searchResults: '検索結果',
        resultsFor: '検索結果:',
        noMatches: '一致する結果が見つかりませんでした:',
        title: 'タイトル',
        type: 'タイプ',
        description: '説明',
        genre: 'ジャンル（カンマ区切り）',
        videoUrl: '動画URL',
        thumbnailUrl: 'サムネイルURL',
        joinCommunity: 'コミュニティに参加',
        copyright: "Copyright © 2025 - 2025 SeikoTV. 'SeikoTV', the SeikoTV logos and name belong to SeikoTV.",
        playTrailer: '予告編を再生',
        playMovie: '映画を再生',
        playEpisode: 'エピソードを再生',
        episodes: 'エピソード',
        genres: 'ジャンル',
        movie: '映画',
        series: 'シリーズ',
        addToList: 'リストに追加',
        removeFromList: 'リストから削除',
        emptyWatchlist: 'ウォッチリストは空です。',
        joinCall: 'ルームに参加',
        roomName: 'ルーム名',
        enterRoomName: 'ルーム名を入力',
        displayName: '表示名',
        enterDisplayName: '名前を入力',
        callsDescription: '無料のビデオ通話ルームを作成または参加して、他のファンとチャットしましょう！',
        recommendedForYou: 'あなたへのおすすめ',
        continueWatching: '視聴を続ける',
        changelog: '更新履歴',
        close: '閉じる',
        changelogTitle: 'SeikoTVの新機能',
        skipIntro: 'イントロをスキップ',
        nextEpisode: '次のエピソード',
        generatingRecommendations: 'おすすめを生成中...',
        genresLabel: 'ジャンル:',
        releaseLabel: '公開年:',
        ratingLabel: '評価:',
        exit: '終了',
        donate: '寄付する :)',
        clearHistory: '履歴を消去',
        searchHistory: '検索履歴',
        privacyPolicy: 'プライバシーポリシー',
        termsOfService: '利用規約',
        aboutUs: 'SeikoTVについて',
        aboutText1: 'SeikoTVは、最高のエンターテイメントをお届けすることに専念する主要なビデオストリーミングプラットフォームです。魅力的なドラマや陽気なコメディからアクション満載の冒険まで、厳選されたライブラリは誰にでも楽しめるものを提供しています。',
        aboutText2: '私たちはクリエイターを支援し、ユニークな声が届く場所を提供することに取り組んでいます。今すぐコミュニティに参加して、次のお気に入りのシリーズや映画を見つけてください。',
        quality: '画質',
        auto: '自動',
        audio: '音声',
        subtitles: '字幕',
        off: 'オフ',
        settings: '設定',
        speed: '速度',
        autoPlay: '自動再生',
        nextEpisodeIn: '次のエピソードまで',
        cancel: 'キャンセル',
        playNow: '今すぐ再生',
        minigamesTitle: 'アーケードゾーン',
        minigamesDesc: '休憩して、素晴らしいミニゲームをプレイしましょう！',
        playGame: 'ゲームをプレイ',
        comingSoon: '近日公開',
        dataSaver: 'データセーバー',
        spatialAudio: '空間オーディオ',
        spatialAudioDesc: '没入型3Dサウンド',
        secretGenre1: 'SFアニメ',
        secretGenre2: '伝記ドキュメンタリー',
        secretGenre3: 'B級ホラー',
        secretUnlocked: '秘密のジャンルが解除されました！'
    },
};

// Helper to fill the rest with English to prevent runtime errors if a key is missing
LANGUAGES.forEach(lang => {
    if (!TRANSLATIONS[lang.code]) {
        TRANSLATIONS[lang.code] = { ...TRANSLATIONS['en'] };
    }
});
